-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차들의 대여 금액 구하기
WITH CAR_RENTAL_FOR30 AS (
    SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(30*(1-DISCOUNT_RATE/100)*C.DAILY_FEE) FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE
    WHERE D.DURATION_TYPE = '30일 이상'
    AND C.CAR_TYPE IN ('세단','SUV')
)

-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차들 중에서 대여 가능한 것만 뽑기
SELECT CAR_ID, CAR_TYPE, FEE
FROM CAR_RENTAL_FOR30 R
WHERE NOT EXISTS ( -- 다른 사람이 대여하고 있는 날이 하나도 없는지 확인
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE R.CAR_ID = H.CAR_ID
    AND H.START_DATE<'2022-11-30'
    AND H.END_DATE>='2022-11-01'
)
AND FEE >=500000 AND FEE <2000000
ORDER BY FEE DESC, R.CAR_TYPE ASC, R.CAR_ID DESC