SELECT I.REST_ID REST_ID, 
    I.REST_NAME REST_NAME, 
    I.FOOD_TYPE FOOD_TYPE, 
    I.FAVORITES FAVORITES, 
    I.ADDRESS ADDRESS, 
    ROUND(AVG(V.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW V
ON I.REST_ID = V.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;